intf_libs = # Interface dependencies.
impl_libs = # Implementation dependencies.
#import impl_libs += libhello%lib{hello}

lib{functional}: {hxx ixx txx cxx}{**} $impl_libs $intf_libs

hxx{export}@./: cxx.importable = false

# Build options.
#
cxx.poptions =+ "-I$out_root" "-I$src_root"

{hbmia obja}{*}: cxx.poptions += -DFUNCTIONAL_STATIC_BUILD
{hbmis objs}{*}: cxx.poptions += -DFUNCTIONAL_SHARED_BUILD

# Export options.
#
lib{functional}:
{
  cxx.export.poptions = "-I$out_root" "-I$src_root"
  cxx.export.libs = $intf_libs
}

liba{functional}: cxx.export.poptions += -DFUNCTIONAL_STATIC
libs{functional}: cxx.export.poptions += -DFUNCTIONAL_SHARED

# For pre-releases use the complete version to make sure they cannot be used
# in place of another pre-release or the final version. See the version module
# for details on the version.* variable values.
#
if $version.pre_release
  lib{functional}: bin.lib.version = @"-$version.project_id"
else
  lib{functional}: bin.lib.version = @"-$version.major.$version.minor"

# Install into the functional/ subdirectory of, say, /usr/include/
# recreating subdirectories.
#
{hxx ixx txx}{*}:
{
  install         = include/functional/
  install.subdirs = true
}
