/**
 *
 *  api_rest.cc
 *  This file is generated by drogon_ctl
 *
 */

#include "api_rest.h"
#include <string>

using namespace api;

void rest::getOne(const HttpRequestPtr &req,
                  std::function<void(const HttpResponsePtr &)> &&callback,
                  std::string &&id)
{
}

void rest::get(const HttpRequestPtr &req,
               std::function<void(const HttpResponsePtr &)> &&callback)
{
}
void rest::create(const HttpRequestPtr &req,
                  std::function<void(const HttpResponsePtr &)> &&callback)
{
}
void rest::updateOne(const HttpRequestPtr &req,
                     std::function<void(const HttpResponsePtr &)> &&callback,
                     std::string &&id)
{
}

/*
void rest::update(const HttpRequestPtr &req,
                  std::function<void(const HttpResponsePtr &)> &&callback)
{

}*/

void rest::deleteOne(const HttpRequestPtr &req,
                     std::function<void(const HttpResponsePtr &)> &&callback,
                     std::string &&id)
{
}
